# -*- coding: utf-8 -*-
"""Registry of public, key-free job sources."""
from . import (
    accenture,
    bradesco,
    ats_boards,
    company_careers,
    recrutei,
    empregare,
    experian,
    geekhunter,
    github_boards,
    requested_careers,
    requested_portals_aug2026,
    gupy,
    inhire,
    oracle_careers,
    remote_boards,
    totvs,
    solides,
    themuse,
    wwr,
    wise,
)

REGISTRY = [
    ("inhire", inhire.fetch),
    ("empregare", empregare.fetch),
    ("experian", experian.fetch),
    ("recrutei", recrutei.fetch),
    ("totvs", totvs.fetch),
    ("accenture", accenture.fetch),
    ("bradesco", bradesco.fetch),
    ("gupy", gupy.fetch),
    ("solides", solides.fetch),
    ("geekhunter", geekhunter.fetch),
    ("github", github_boards.fetch),
    ("docusign", requested_careers.fetch_docusign),
    ("dbccompany", requested_careers.fetch_dbccompany),
    ("providerit", requested_portals_aug2026.fetch_providerit),
    ("fiserv", requested_portals_aug2026.fetch_fiserv),
    ("metalfrio", requested_portals_aug2026.fetch_metalfrio),
    ("revolut", requested_portals_aug2026.fetch_revolut),
    ("inlog", requested_portals_aug2026.fetch_inlog),
    ("nestle", requested_portals_aug2026.fetch_nestle),
    ("stone", company_careers.fetch_stone),
    ("ifood", company_careers.fetch_ifood),
    ("picpay", oracle_careers.fetch_picpay),
    ("bancooriginal", oracle_careers.fetch_bancooriginal),
    ("braskem", oracle_careers.fetch_braskem),
    ("gmfinancial", oracle_careers.fetch_gmfinancial),
    ("dell", oracle_careers.fetch_dell),
    ("arcelormittal", oracle_careers.fetch_arcelormittal),
    ("grupomateus", oracle_careers.fetch_grupomateus),
    ("autozone", oracle_careers.fetch_autozone),
    ("nov", oracle_careers.fetch_nov),
    ("arcorbrasil", oracle_careers.fetch_arcorbrasil),
    ("themuse", themuse.fetch),
    ("remotive", remote_boards.fetch_remotive),
    ("jobicy", remote_boards.fetch_jobicy),
    ("remoteok", remote_boards.fetch_remoteok),
    ("himalayas", remote_boards.fetch_himalayas),
    ("workingnomads", remote_boards.fetch_workingnomads),
    ("arbeitnow", remote_boards.fetch_arbeitnow),
    ("weworkremotely", wwr.fetch),
    ("wise", wise.fetch),
    ("greenhouse", ats_boards.fetch_greenhouse),
    ("lever", ats_boards.fetch_lever),
    ("ashby", ats_boards.fetch_ashby),
]
