# -*- coding: utf-8 -*-
"""Registry of public, key-free job sources."""
from . import (
    ats_boards,
    company_careers,
    recrutei,
    empregare,
    geekhunter,
    github,
    gupy,
    inhire,
    oracle_careers,
    remote_boards,
    totvs,
    solides,
    themuse,
    wwr,
)

REGISTRY = [
    ("inhire", inhire.fetch),
    ("empregare", empregare.fetch),
    ("recrutei", recrutei.fetch),
    ("totvs", totvs.fetch),
    ("gupy", gupy.fetch),
    ("solides", solides.fetch),
    ("geekhunter", geekhunter.fetch),
    ("github", github.fetch),
    ("stone", company_careers.fetch_stone),
    ("ifood", company_careers.fetch_ifood),
    ("picpay", oracle_careers.fetch_picpay),
    ("bancooriginal", oracle_careers.fetch_bancooriginal),
    ("braskem", oracle_careers.fetch_braskem),
    ("gmfinancial", oracle_careers.fetch_gmfinancial),
    ("dell", oracle_careers.fetch_dell),
    ("arcelormittal", oracle_careers.fetch_arcelormittal),
    ("grupomateus", oracle_careers.fetch_grupomateus),
    ("autozone", oracle_careers.fetch_autozone),
    ("nov", oracle_careers.fetch_nov),
    ("arcorbrasil", oracle_careers.fetch_arcorbrasil),
    ("themuse", themuse.fetch),
    ("remotive", remote_boards.fetch_remotive),
    ("jobicy", remote_boards.fetch_jobicy),
    ("remoteok", remote_boards.fetch_remoteok),
    ("himalayas", remote_boards.fetch_himalayas),
    ("workingnomads", remote_boards.fetch_workingnomads),
    ("arbeitnow", remote_boards.fetch_arbeitnow),
    ("weworkremotely", wwr.fetch),
    ("greenhouse", ats_boards.fetch_greenhouse),
    ("lever", ats_boards.fetch_lever),
    ("ashby", ats_boards.fetch_ashby),
]
